"use client";

import { useEffect, useState } from "react";

type Source = { id: string; name: string };
type Item = { space: Source; folders: Array<{ id: string; name: string; lists: Source[] }>; lists: Source[] };
type Job = { id: string; status: string; cursor: number; total: number; imported: number; failed: number };

export default function ClickUpImportPage() {
  const [workspaces, setWorkspaces] = useState<Source[]>([]); const [source, setSource] = useState(""); const [hierarchy, setHierarchy] = useState<Item[]>([]); const [selected, setSelected] = useState<Record<string, { space_id: string; folder_id?: string; list_id: string }>>({}); const [preview, setPreview] = useState<{ lists: number; tasks: number; assignee_emails: string[] } | null>(null); const [job, setJob] = useState<Job | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/admin/imports/clickup/workspaces").then((r) => r.json()).then((v) => setWorkspaces(v.teams ?? [])).catch(() => setMessage("Could not load ClickUp workspaces")); }, []);
  async function loadHierarchy() { const r = await fetch("/api/admin/imports/clickup/hierarchy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source_workspace_id: source }) }); const v = await r.json(); setHierarchy(v.items ?? []); }
  function toggle(value: { space_id: string; folder_id?: string; list_id: string }) { setSelected((current) => { const next = { ...current }; if (next[value.list_id]) delete next[value.list_id]; else next[value.list_id] = value; return next; }); setPreview(null); }
  async function runPreview() { const r = await fetch("/api/admin/imports/clickup/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source_workspace_id: source, list_ids: Object.keys(selected) }) }); setPreview(await r.json()); }
  async function start() { if (!preview) return; const r = await fetch("/api/admin/imports/clickup/jobs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source_workspace_id: source, selected_source_ids: Object.values(selected), total: preview.tasks, confirmation: true }) }); const created = await r.json(); setJob(created); setMessage("Import queued. Use Resume to process the next bounded batch."); }
  async function resume() { if (!job) return; const r = await fetch(`/api/admin/imports/clickup/jobs/${job.id}/resume`, { method: "POST" }); setJob(await r.json()); }
  async function cancel() { if (!job) return; await fetch(`/api/admin/imports/clickup/jobs/${job.id}/cancel`, { method: "POST" }); setJob({ ...job, status: "cancelled" }); }
  return <main className="mx-auto max-w-4xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">ClickUp migration</h1><p className="text-sm text-muted-foreground">Import selected active work into this Upflow workspace. ClickUp credentials stay on the server.</p></div><section className="space-y-3 rounded-lg border p-4"><label className="block text-sm font-medium">ClickUp workspace<select className="mt-1 block w-full rounded border p-2" value={source} onChange={(e) => setSource(e.target.value)}><option value="">Select workspace</option>{workspaces.map((w) => <option key={w.id} value={w.id}>{w.name}</option>)}</select></label><button className="rounded bg-primary px-3 py-2 text-primary-foreground disabled:opacity-50" disabled={!source} onClick={loadHierarchy}>Load spaces and lists</button></section>{hierarchy.length > 0 && <section className="space-y-4 rounded-lg border p-4"><h2 className="font-semibold">Select lists</h2>{hierarchy.map((item) => <div key={item.space.id}><h3 className="font-medium">{item.space.name}</h3><div className="grid gap-2 pl-4 sm:grid-cols-2">{item.lists.map((list) => <label key={list.id} className="flex gap-2 text-sm"><input type="checkbox" checked={Boolean(selected[list.id])} onChange={() => toggle({ space_id: item.space.id, list_id: list.id })} />{list.name}</label>)}{item.folders.map((folder) => <div key={folder.id} className="col-span-full"><p className="text-sm font-medium text-muted-foreground">{folder.name}</p>{folder.lists.map((list) => <label key={list.id} className="ml-4 flex gap-2 text-sm"><input type="checkbox" checked={Boolean(selected[list.id])} onChange={() => toggle({ space_id: item.space.id, folder_id: folder.id, list_id: list.id })} />{list.name}</label>)}</div>)}</div></div>)}<div className="flex gap-2"><button className="rounded border px-3 py-2 disabled:opacity-50" disabled={!Object.keys(selected).length} onClick={runPreview}>Preview</button>{preview && <button className="rounded bg-primary px-3 py-2 text-primary-foreground" onClick={start}>Confirm and queue import</button>}</div>{preview && <p className="text-sm">Preview: {preview.lists} lists, {preview.tasks} active tasks, {preview.assignee_emails.length} matched-by-email candidates.</p>}</section>}{job && <section className="space-y-3 rounded-lg border p-4"><h2 className="font-semibold">Migration job</h2><p className="text-sm">{job.status}: {job.imported} imported, {job.failed} failed, {job.cursor} of {job.total} list batches processed.</p><div className="flex gap-2"><button className="rounded bg-primary px-3 py-2 text-primary-foreground disabled:opacity-50" disabled={job.status === "completed" || job.status === "cancelled"} onClick={resume}>Resume next batch</button><button className="rounded border px-3 py-2 disabled:opacity-50" disabled={job.status === "completed" || job.status === "cancelled"} onClick={cancel}>Cancel</button></div></section>}{message && <p role="status" className="text-sm">{message}</p>}</main>;
}
