"use client";

import * as React from "react";

export type Language = "en" | "pt-BR";

type TranslationVars = Record<string, string | number>;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, vars?: TranslationVars) => string;
}

const STORAGE_KEY = "upflow.language";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "language.english": "English",
    "language.portugueseBrazil": "Portuguese (Brazil)",
    "language.shortEnglish": "EN",
    "language.shortPortuguese": "PT-BR",
    "language.toggle": "Change language",
    "header.searchPlaceholder": "Search {title}, projects, tasks, docs...",
    "header.notifications": "Notifications",
    "header.markAllRead": "Mark all read",
    "header.allCaughtUp": "You're all caught up",
    "header.newProject": "New Project",
    "nav.dashboard": "Dashboard",
    "nav.team": "Team",
    "nav.timeTracking": "Time tracking",
    "nav.inbox": "Inbox",
    "nav.calendar": "Calendar",
    "nav.projects": "Projects",
    "nav.clients": "Clients",
    "sidebar.show": "Show sidebar",
    "sidebar.hide": "Hide sidebar",
    "sidebar.help": "Help",
    "sidebar.signOut": "Sign out",
    "sidebar.navigation": "Navigation",
    "sidebar.workspace": "Workspace",
    "sidebar.spaces": "Spaces",
    "sidebar.collapseAll": "Collapse all",
    "sidebar.newSpace": "New space",
    "sidebar.searchSpaces": "Search spaces...",
    "sidebar.clearSearch": "Clear sidebar search",
    "sidebar.loading": "Loading...",
    "sidebar.noSearchMatches": "No spaces, folders, or lists match {query}.",
    "sidebar.noSpaces": "No spaces yet.",
    "sidebar.createFirstSpace": "Create your first space",
    "workspace.loading": "Loading workspace...",
    "workspace.namePrompt": "Workspace name",
    "workspace.switchError": "Could not switch workspace",
    "workspace.createError": "Could not create workspace",
    "workspace.new": "New workspace",
    "auth.signedOut": "Signed out",
    "auth.signOutFailed": "Sign-out failed; please try again",
    "common.cancel": "Cancel",
    "common.create": "Create",
    "common.delete": "Delete",
    "common.open": "Open",
    "common.updated": "Updated",
    "common.failedToUpdate": "Failed to update",
    "common.none": "None",
    "common.anyone": "Anyone",
    "common.unassigned": "Unassigned",
    "common.creating": "Creating...",
    "status.todo": "To Do",
    "status.inProgress": "In Progress",
    "status.done": "Done",
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "dashboard.title": "Dashboard",
    "dashboard.commandCenter": "Agency Operations Command Center",
    "dashboard.good": "Good {greeting}, {name}",
    "dashboard.hi": "Hi {name}",
    "dashboard.greeting.morning": "morning",
    "dashboard.greeting.afternoon": "afternoon",
    "dashboard.greeting.evening": "evening",
    "dashboard.summary": "Clients, campaigns, deliverables, meetings, time, risks, workload, and revenue in one operational view.",
    "dashboard.risks": "{count} risks",
    "dashboard.tasksComplete": "{progress}% deliverables complete",
    "dashboard.timerRunning": "Timer running",
    "dashboard.noActiveTimer": "No active timer",
    "dashboard.operationalPulse": "Operational pulse",
    "dashboard.nextMeeting": "Next meeting",
    "dashboard.noneToday": "None today",
    "dashboard.focusQueue": "Focus queue",
    "dashboard.items": "{count} items",
    "dashboard.openWork": "Open work",
    "dashboard.tasksCount": "{count} deliverables",
    "dashboard.tasks": "Deliverables",
    "dashboard.teamFlags": "Team flags",
    "dashboard.lateOrOverloaded": "Late or overloaded",
    "dashboard.activity": "Activity",
    "dashboard.workspaceTrail": "Workspace trail",
    "dashboard.myUrgentActions": "Urgent client actions",
    "dashboard.urgentHint": "Due today, overdue, or high-priority deliverables",
    "dashboard.meetingsToday": "Meetings today",
    "dashboard.meetingsHint": "Calendar events scheduled today",
    "dashboard.timeToday": "Time today",
    "dashboard.trackedToday": "Tracked entries today",
    "dashboard.projectsAtRisk": "Campaigns at risk",
    "dashboard.projectsRiskHint": "Overdue client work or stale campaigns",
    "dashboard.clientRisk": "Client risk",
    "dashboard.clientRiskHint": "Clients missing activity, contacts, plan data, or delivery movement",
    "dashboard.revenueSnapshot": "Revenue snapshot",
    "dashboard.activeClients": "{count} active clients",
    "dashboard.statusHint": "Delivery status stays one click away from exact records.",
    "dashboard.newTask": "New deliverable",
    "dashboard.completion": "Completion",
    "dashboard.upcoming": "Upcoming",
    "dashboard.upcomingHint": "Deliverables waiting to start",
    "dashboard.inProgress": "In progress",
    "dashboard.inProgressHint": "Currently being worked on",
    "dashboard.completed": "Completed",
    "dashboard.ofTotal": "{progress}% of total",
    "dashboard.teamWorkload": "Team workload",
    "dashboard.membersWithSignals": "{count} members with signals",
    "dashboard.recentActivity": "Recent activity",
    "dashboard.traceableRecords": "{count} traceable records",
    "dashboard.todayFocus": "Today focus",
    "dashboard.todayFocusHint": "The shortest list of work that needs attention now.",
    "dashboard.noFocus": "No urgent focus items right now.",
    "dashboard.taskCreated": "Deliverable created",
    "dashboard.projectCreated": "Project created",
    "dashboard.taskDeleted": "Task deleted",
    "dashboard.couldNotDeleteTask": "Could not delete task",
    "dashboard.couldNotUpdateTask": "Could not update task",
    "dashboard.taskMoved": "Task moved to {status}",
    "projects.project": "Project",
    "projects.newProject": "New Project",
    "projects.projectName": "Project name",
    "projects.projectNamePlaceholder": "e.g. Website Redesign",
    "projects.description": "Description",
    "projects.descriptionPlaceholder": "Brief description of the project...",
    "projects.dueDate": "Due date",
    "projects.createProject": "Create Project",
    "projects.failedCreate": "Failed to create project",
    "projects.backToProjects": "Back to Projects",
    "projects.docs": "Docs",
    "projects.addTask": "Add Task",
    "projects.tasksLabel": "{count} tasks",
    "projects.due": "Due {date}",
    "projects.doneProgress": "{progress}% done",
    "projects.failedToLoad": "Failed to load project",
    "toolbar.list": "List",
    "toolbar.board": "Board",
    "toolbar.searchTasks": "Search tasks...",
    "toolbar.filter": "Filter",
    "toolbar.group": "Group: {label}",
    "toolbar.sort": "Sort: {label}",
    "toolbar.showClosed": "Show closed",
    "toolbar.customFields": "Custom fields",
    "toolbar.columns": "Columns",
    "toolbar.priority": "Priority",
    "toolbar.assignee": "Assignee",
    "toolbar.status": "Status",
    "toolbar.dueDate": "Due date",
    "toolbar.manual": "Manual",
    "toolbar.title": "Title",
    "toolbar.created": "Created",
    "toolbar.clearFilters": "Clear filters",
    "toolbar.sortAscending": "Sort ascending",
    "toolbar.sortDescending": "Sort descending",
    "task.newTask": "New Task",
    "task.taskName": "Task name",
    "task.notesPlaceholder": "Add task notes, client context, or internal instructions...",
    "task.titleRequired": "Title is required",
    "task.createTask": "Create deliverable",
    "task.failedCreate": "Failed to create task",
    "task.clickCycleStatus": "Click to cycle status",
    "task.boardCoverImage": "Board cover image",
    "task.subtasks": "Subtasks",
    "task.addSubtasksLater": "Add subtasks after creating the task from its detail view.",
    "task.deleteConfirm": "Delete this task?",
    "task.deleteSubtaskConfirm": "Delete this subtask?",
    "task.failedDelete": "Failed to delete",
    "task.failedAddComment": "Failed to add comment",
    "task.failedAddReply": "Failed to add reply",
    "task.failedAddSubtask": "Failed to add subtask",
    "task.failedDeleteSubtask": "Failed to delete subtask",
    "task.failedUpdateSubtask": "Failed to update subtask",
    "task.descriptionBrief": "Description / brief",
    "task.structuredBrief": "Structured task brief",
    "task.descriptionPlaceholder": "Add a description...",
    "task.noSubtasks": "No subtasks yet",
    "task.addSubtask": "Add subtask",
    "task.comments": "Comments",
    "task.addComment": "Add a comment...",
    "task.reply": "Reply",
    "taskTemplate.type": "Task type",
    "taskTemplate.general.label": "General task",
    "taskTemplate.creative.label": "Creative / Design",
    "taskTemplate.b2b_marketing.label": "B2B Marketing",
    "taskTemplate.b2c_marketing.label": "B2C Marketing",
    "taskTemplate.commercial.label": "Commercial",
    "taskTemplate.finance.label": "Finance",
    "taskTemplate.production.label": "Production",
    "taskTemplate.technical_support.label": "Technical Support",
    "taskTemplate.admin.label": "General Admin",
    "taskTemplate.general.description": "Simple work item with flexible notes.",
    "taskTemplate.creative.description": "Asset production, design, and approval work.",
    "taskTemplate.b2b_marketing.description": "Lead generation, outbound, and account-based campaigns.",
    "taskTemplate.b2c_marketing.description": "Consumer campaigns, launches, ads, and content.",
    "taskTemplate.commercial.description": "Sales, proposals, contracts, follow-up, and commissions.",
    "taskTemplate.finance.description": "Invoices, payments, commissions, expenses, and cashflow.",
    "taskTemplate.production.description": "Shoots, editing, publishing, deliverables, and production handoffs.",
    "taskTemplate.technical_support.description": "Support tickets, bug reports, access issues, escalations, and resolution notes.",
    "taskTemplate.admin.description": "Internal operations, access, documents, suppliers, and approvals.",
  },
  "pt-BR": {
    "language.english": "Ingles",
    "language.portugueseBrazil": "Portugues (Brasil)",
    "language.shortEnglish": "EN",
    "language.shortPortuguese": "PT-BR",
    "language.toggle": "Alterar idioma",
    "header.searchPlaceholder": "Buscar {title}, projetos, tarefas, docs...",
    "header.notifications": "Notificacoes",
    "header.markAllRead": "Marcar tudo como lido",
    "header.allCaughtUp": "Tudo em dia",
    "header.newProject": "Novo projeto",
    "nav.dashboard": "Dashboard",
    "nav.team": "Equipe",
    "nav.timeTracking": "Controle de tempo",
    "nav.inbox": "Caixa de entrada",
    "nav.calendar": "Calendario",
    "nav.projects": "Projetos",
    "nav.clients": "Clientes",
    "sidebar.show": "Mostrar sidebar",
    "sidebar.hide": "Ocultar sidebar",
    "sidebar.help": "Ajuda",
    "sidebar.signOut": "Sair",
    "sidebar.navigation": "Navegacao",
    "sidebar.workspace": "Workspace",
    "sidebar.spaces": "Espacos",
    "sidebar.collapseAll": "Recolher tudo",
    "sidebar.newSpace": "Novo espaco",
    "sidebar.searchSpaces": "Buscar espacos...",
    "sidebar.clearSearch": "Limpar busca da sidebar",
    "sidebar.loading": "Carregando...",
    "sidebar.noSearchMatches": "Nenhum espaco, pasta ou lista corresponde a {query}.",
    "sidebar.noSpaces": "Nenhum espaco ainda.",
    "sidebar.createFirstSpace": "Criar primeiro espaco",
    "workspace.loading": "Carregando workspace...",
    "workspace.namePrompt": "Nome do workspace",
    "workspace.switchError": "Nao foi possivel trocar de workspace",
    "workspace.createError": "Nao foi possivel criar workspace",
    "workspace.new": "Novo workspace",
    "auth.signedOut": "Sessao encerrada",
    "auth.signOutFailed": "Falha ao sair; tente novamente",
    "common.cancel": "Cancelar",
    "common.create": "Criar",
    "common.delete": "Excluir",
    "common.open": "Abrir",
    "common.updated": "Atualizado",
    "common.failedToUpdate": "Falha ao atualizar",
    "common.none": "Nenhum",
    "common.anyone": "Qualquer pessoa",
    "common.unassigned": "Sem responsavel",
    "common.creating": "Criando...",
    "status.todo": "A fazer",
    "status.inProgress": "Em andamento",
    "status.done": "Concluido",
    "priority.low": "Baixa",
    "priority.medium": "Media",
    "priority.high": "Alta",
    "dashboard.title": "Dashboard",
    "dashboard.commandCenter": "Centro de Operacoes da Agencia",
    "dashboard.good": "Boa {greeting}, {name}",
    "dashboard.hi": "Ola {name}",
    "dashboard.greeting.morning": "manha",
    "dashboard.greeting.afternoon": "tarde",
    "dashboard.greeting.evening": "noite",
    "dashboard.summary": "Clientes, campanhas, entregas, reunioes, tempo, riscos, carga da equipe e receita em uma visao operacional.",
    "dashboard.risks": "{count} riscos",
    "dashboard.tasksComplete": "{progress}% das entregas concluidas",
    "dashboard.timerRunning": "Timer em andamento",
    "dashboard.noActiveTimer": "Nenhum timer ativo",
    "dashboard.operationalPulse": "Pulso operacional",
    "dashboard.nextMeeting": "Proxima reuniao",
    "dashboard.noneToday": "Nenhuma hoje",
    "dashboard.focusQueue": "Fila de foco",
    "dashboard.items": "{count} itens",
    "dashboard.openWork": "Trabalho aberto",
    "dashboard.tasksCount": "{count} entregas",
    "dashboard.tasks": "Entregas",
    "dashboard.teamFlags": "Alertas da equipe",
    "dashboard.lateOrOverloaded": "Atrasados ou sobrecarregados",
    "dashboard.activity": "Atividade",
    "dashboard.workspaceTrail": "Historico do workspace",
    "dashboard.myUrgentActions": "Acoes urgentes de clientes",
    "dashboard.urgentHint": "Para hoje, atrasadas ou entregas de alta prioridade",
    "dashboard.meetingsToday": "Reunioes de hoje",
    "dashboard.meetingsHint": "Eventos agendados para hoje",
    "dashboard.timeToday": "Tempo hoje",
    "dashboard.trackedToday": "Entradas registradas hoje",
    "dashboard.projectsAtRisk": "Campanhas em risco",
    "dashboard.projectsRiskHint": "Trabalho de cliente atrasado ou campanhas paradas",
    "dashboard.clientRisk": "Risco de clientes",
    "dashboard.clientRiskHint": "Clientes sem atividade, contatos, plano ou movimento de entrega",
    "dashboard.revenueSnapshot": "Resumo de receita",
    "dashboard.activeClients": "{count} clientes ativos",
    "dashboard.statusHint": "Status de entrega fica a um clique dos registros exatos.",
    "dashboard.newTask": "Nova entrega",
    "dashboard.completion": "Conclusao",
    "dashboard.upcoming": "Pendentes",
    "dashboard.upcomingHint": "Entregas aguardando inicio",
    "dashboard.inProgress": "Em andamento",
    "dashboard.inProgressHint": "Em execucao agora",
    "dashboard.completed": "Concluidas",
    "dashboard.ofTotal": "{progress}% do total",
    "dashboard.teamWorkload": "Carga da equipe",
    "dashboard.membersWithSignals": "{count} membros com sinais",
    "dashboard.recentActivity": "Atividade recente",
    "dashboard.traceableRecords": "{count} registros rastreaveis",
    "dashboard.todayFocus": "Foco de hoje",
    "dashboard.todayFocusHint": "A lista mais curta do que precisa de atencao agora.",
    "dashboard.noFocus": "Nenhum item urgente agora.",
    "dashboard.taskCreated": "Entrega criada",
    "dashboard.projectCreated": "Projeto criado",
    "dashboard.taskDeleted": "Tarefa excluida",
    "dashboard.couldNotDeleteTask": "Nao foi possivel excluir a tarefa",
    "dashboard.couldNotUpdateTask": "Nao foi possivel atualizar a tarefa",
    "dashboard.taskMoved": "Tarefa movida para {status}",
    "projects.project": "Projeto",
    "projects.newProject": "Novo projeto",
    "projects.projectName": "Nome do projeto",
    "projects.projectNamePlaceholder": "ex.: Redesign do site",
    "projects.description": "Descricao",
    "projects.descriptionPlaceholder": "Breve descricao do projeto...",
    "projects.dueDate": "Data de vencimento",
    "projects.createProject": "Criar projeto",
    "projects.failedCreate": "Falha ao criar projeto",
    "projects.backToProjects": "Voltar para Projetos",
    "projects.docs": "Docs",
    "projects.addTask": "Adicionar tarefa",
    "projects.tasksLabel": "{count} tarefas",
    "projects.due": "Vence em {date}",
    "projects.doneProgress": "{progress}% concluido",
    "projects.failedToLoad": "Falha ao carregar projeto",
    "toolbar.list": "Lista",
    "toolbar.board": "Quadro",
    "toolbar.searchTasks": "Buscar tarefas...",
    "toolbar.filter": "Filtro",
    "toolbar.group": "Grupo: {label}",
    "toolbar.sort": "Ordenar: {label}",
    "toolbar.showClosed": "Mostrar concluidas",
    "toolbar.customFields": "Campos personalizados",
    "toolbar.columns": "Colunas",
    "toolbar.priority": "Prioridade",
    "toolbar.assignee": "Responsavel",
    "toolbar.status": "Status",
    "toolbar.dueDate": "Data de vencimento",
    "toolbar.manual": "Manual",
    "toolbar.title": "Titulo",
    "toolbar.created": "Criado",
    "toolbar.clearFilters": "Limpar filtros",
    "toolbar.sortAscending": "Ordenar crescente",
    "toolbar.sortDescending": "Ordenar decrescente",
    "task.newTask": "Nova tarefa",
    "task.taskName": "Nome da tarefa",
    "task.notesPlaceholder": "Adicione notas, contexto do cliente ou instrucoes internas...",
    "task.titleRequired": "Titulo e obrigatorio",
    "task.createTask": "Criar entrega",
    "task.failedCreate": "Falha ao criar tarefa",
    "task.clickCycleStatus": "Clique para alternar status",
    "task.boardCoverImage": "Imagem de capa no quadro",
    "task.subtasks": "Subtarefas",
    "task.addSubtasksLater": "Adicione subtarefas depois de criar a tarefa pela tela de detalhes.",
    "task.deleteConfirm": "Excluir esta tarefa?",
    "task.deleteSubtaskConfirm": "Excluir esta subtarefa?",
    "task.failedDelete": "Falha ao excluir",
    "task.failedAddComment": "Falha ao adicionar comentario",
    "task.failedAddReply": "Falha ao adicionar resposta",
    "task.failedAddSubtask": "Falha ao adicionar subtarefa",
    "task.failedDeleteSubtask": "Falha ao excluir subtarefa",
    "task.failedUpdateSubtask": "Falha ao atualizar subtarefa",
    "task.descriptionBrief": "Descricao / briefing",
    "task.structuredBrief": "Briefing estruturado",
    "task.descriptionPlaceholder": "Adicione uma descricao...",
    "task.noSubtasks": "Nenhuma subtarefa ainda",
    "task.addSubtask": "Adicionar subtarefa",
    "task.comments": "Comentarios",
    "task.addComment": "Adicionar comentario...",
    "task.reply": "Responder",
    "taskTemplate.type": "Tipo de tarefa",
    "taskTemplate.general.label": "Tarefa geral",
    "taskTemplate.creative.label": "Criativo / Design",
    "taskTemplate.b2b_marketing.label": "Marketing B2B",
    "taskTemplate.b2c_marketing.label": "Marketing B2C",
    "taskTemplate.commercial.label": "Comercial",
    "taskTemplate.finance.label": "Financeiro",
    "taskTemplate.production.label": "Producao",
    "taskTemplate.technical_support.label": "Suporte tecnico",
    "taskTemplate.admin.label": "Administrativo geral",
    "taskTemplate.general.description": "Item simples de trabalho com notas flexiveis.",
    "taskTemplate.creative.description": "Producao de assets, design e aprovacoes.",
    "taskTemplate.b2b_marketing.description": "Geracao de leads, outbound e campanhas por conta.",
    "taskTemplate.b2c_marketing.description": "Campanhas de consumo, lancamentos, anuncios e conteudo.",
    "taskTemplate.commercial.description": "Vendas, propostas, contratos, follow-up e comissoes.",
    "taskTemplate.finance.description": "Notas, pagamentos, comissoes, despesas e caixa.",
    "taskTemplate.production.description": "Gravacoes, edicao, publicacao, entregaveis e handoffs.",
    "taskTemplate.technical_support.description": "Tickets de suporte, bugs, acessos, escalacoes e notas de resolucao.",
    "taskTemplate.admin.description": "Operacoes internas, acessos, documentos, fornecedores e aprovacoes.",
  },
};

const LanguageContext = React.createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => null,
  toggleLanguage: () => null,
  t: (key) => key,
});

function normalizeLanguage(value: string | null): Language | null {
  if (value === "en" || value === "pt-BR") return value;
  return null;
}

function interpolate(value: string, vars?: TranslationVars) {
  if (!vars) return value;
  return value.replace(/\{(\w+)\}/g, (_, key: string) =>
    Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : `{${key}}`,
  );
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = React.useState<Language>("en");

  React.useEffect(() => {
    try {
      const stored = normalizeLanguage(localStorage.getItem(STORAGE_KEY));
      if (stored) setLanguageState(stored);
    } catch {
      // localStorage can be unavailable in privacy modes; English stays as default.
    }
  }, []);

  const setLanguage = React.useCallback((next: Language) => {
    setLanguageState(next);
    try {
      localStorage.setItem(STORAGE_KEY, next);
    } catch {
      // Non-persistent language selection is still usable for the current session.
    }
  }, []);

  React.useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dataset.language = language;
  }, [language]);

  const value = React.useMemo<LanguageContextType>(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage(language === "en" ? "pt-BR" : "en"),
      t: (key, vars) => {
        const localized = translations[language][key] ?? translations.en[key] ?? key;
        return interpolate(localized, vars);
      },
    }),
    [language, setLanguage],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return React.useContext(LanguageContext);
}
