"use client";

import * as React from "react";

export type Language = "en" | "pt-BR";

type TranslationVars = Record<string, string | number>;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, vars?: TranslationVars) => string;
}

const STORAGE_KEY = "upflow.language";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "language.english": "English",
    "language.portugueseBrazil": "Portuguese (Brazil)",
    "language.shortEnglish": "EN",
    "language.shortPortuguese": "PT-BR",
    "language.toggle": "Change language",
    "header.searchPlaceholder": "Search {title}, projects, tasks, docs...",
    "header.notifications": "Notifications",
    "header.markAllRead": "Mark all read",
    "header.allCaughtUp": "You're all caught up",
    "header.newProject": "New Project",
    "nav.dashboard": "Dashboard",
    "nav.team": "Team",
    "nav.timeTracking": "Time tracking",
    "nav.inbox": "Inbox",
    "nav.calendar": "Calendar",
    "nav.projects": "Projects",
    "nav.clients": "Clients",
    "sidebar.show": "Show sidebar",
    "sidebar.hide": "Hide sidebar",
    "sidebar.help": "Help",
    "sidebar.signOut": "Sign out",
    "sidebar.navigation": "Navigation",
    "sidebar.workspace": "Workspace",
    "sidebar.spaces": "Spaces",
    "sidebar.collapseAll": "Collapse all",
    "sidebar.newSpace": "New space",
    "sidebar.searchSpaces": "Search spaces...",
    "sidebar.clearSearch": "Clear sidebar search",
    "sidebar.loading": "Loading...",
    "sidebar.noSearchMatches": "No spaces, folders, or lists match {query}.",
    "sidebar.noSpaces": "No spaces yet.",
    "sidebar.createFirstSpace": "Create your first space",
    "workspace.loading": "Loading workspace...",
    "workspace.namePrompt": "Workspace name",
    "workspace.switchError": "Could not switch workspace",
    "workspace.createError": "Could not create workspace",
    "workspace.new": "New workspace",
    "auth.signedOut": "Signed out",
    "auth.signOutFailed": "Sign-out failed; please try again",
    "common.cancel": "Cancel",
    "common.create": "Create",
    "common.delete": "Delete",
    "common.open": "Open",
    "common.updated": "Updated",
    "common.failedToUpdate": "Failed to update",
    "common.none": "None",
    "common.anyone": "Anyone",
    "common.unassigned": "Unassigned",
    "common.creating": "Creating...",
    "common.loading": "Loading...",
    "common.retry": "Retry",
    "common.refresh": "Refresh",
    "common.save": "Save",
    "common.saving": "Saving...",
    "common.close": "Close",
    "common.done": "Done",
    "common.add": "Add",
    "common.generate": "Generate",
    "common.member": "Member",
    "common.admin": "Admin",
    "common.owner": "Owner",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.sent": "sent",
    "common.accepted": "accepted",
    "common.failed": "failed",
    "common.selected": "Selected",
    "status.todo": "To Do",
    "status.inProgress": "In Progress",
    "status.done": "Done",
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "dashboard.title": "Dashboard",
    "dashboard.commandCenter": "Agency Operations Command Center",
    "dashboard.good": "Good {greeting}, {name}",
    "dashboard.hi": "Hi {name}",
    "dashboard.greeting.morning": "morning",
    "dashboard.greeting.afternoon": "afternoon",
    "dashboard.greeting.evening": "evening",
    "dashboard.summary": "Clients, campaigns, deliverables, meetings, time, risks, workload, and revenue in one operational view.",
    "dashboard.risks": "{count} risks",
    "dashboard.tasksComplete": "{progress}% deliverables complete",
    "dashboard.timerRunning": "Timer running",
    "dashboard.noActiveTimer": "No active timer",
    "dashboard.operationalPulse": "Operational pulse",
    "dashboard.nextMeeting": "Next meeting",
    "dashboard.noneToday": "None today",
    "dashboard.focusQueue": "Focus queue",
    "dashboard.items": "{count} items",
    "dashboard.quickCreate": "Quick create",
    "dashboard.openWork": "Open work",
    "dashboard.tasksCount": "{count} deliverables",
    "dashboard.tasks": "Deliverables",
    "dashboard.teamFlags": "Team flags",
    "dashboard.lateOrOverloaded": "Overdue or 8+ open tasks",
    "dashboard.activity": "Activity",
    "dashboard.workspaceTrail": "Workspace trail",
    "dashboard.myUrgentActions": "Urgent assigned tasks",
    "dashboard.urgentHint": "Due today, overdue, or high-priority deliverables",
    "dashboard.meetingsToday": "Meetings today",
    "dashboard.meetingsHint": "Calendar events scheduled today",
    "dashboard.timeToday": "Time today",
    "dashboard.trackedToday": "Tracked entries today",
    "dashboard.projectsAtRisk": "Campaigns at risk",
    "dashboard.projectsRiskHint": "Overdue tasks or no activity in 7 days",
    "dashboard.clientRisk": "Client risk",
    "dashboard.clientRiskHint": "Clients with overdue work, missing setup, or no recent activity",
    "dashboard.revenueSnapshot": "Revenue snapshot",
    "dashboard.activeClients": "{count} active clients",
    "dashboard.statusHint": "Delivery status stays one click away from exact records.",
    "dashboard.newTask": "New deliverable",
    "dashboard.completion": "Completion",
    "dashboard.upcoming": "Upcoming",
    "dashboard.upcomingHint": "Deliverables waiting to start",
    "dashboard.inProgress": "In progress",
    "dashboard.inProgressHint": "Currently being worked on",
    "dashboard.completed": "Completed",
    "dashboard.ofTotal": "{progress}% of total",
    "dashboard.teamWorkload": "Team workload",
    "dashboard.membersWithSignals": "{count} members with signals",
    "dashboard.recentActivity": "Recent activity",
    "dashboard.traceableRecords": "{count} traceable records",
    "dashboard.noRecentActivity": "No recent activity",
    "dashboard.noRecentActivityHint": "Meaningful workspace operations will be listed here.",
    "dashboard.noTrackedTime": "No tracked time today",
    "dashboard.noTrackedTimeHint": "Start a timer to create the first real time entry.",
    "dashboard.totalToday": "Total today",
    "dashboard.trackedTimeFallback": "Tracked time",
    "dashboard.running": "running",
    "dashboard.logged": "logged",
    "dashboard.noMeetings": "No meetings today",
    "dashboard.noMeetingsHint": "Calendar events created in this workspace appear here.",
    "dashboard.addMeeting": "Add meeting",
    "dashboard.noProjectsAtRisk": "No projects at risk",
    "dashboard.noProjectsAtRiskHint": "Risk rules currently check overdue tasks and lack of recent activity.",
    "dashboard.noClientsAtRisk": "No clients at risk",
    "dashboard.noClientsAtRiskHint": "Client risk checks linked projects, contacts, overdue work, contract value, and recent activity.",
    "dashboard.notEnoughClientData": "Not enough client data yet",
    "dashboard.notEnoughClientDataHint": "Client health appears after clients have linked work, contacts, plan data, or activity.",
    "dashboard.noProject": "No project",
    "dashboard.due": "due {date}",
    "dashboard.noWorkloadTasks": "No open assigned tasks behind this workload signal.",
    "dashboard.overdueCount": "{count} overdue",
    "dashboard.openTasksCount": "{count} open tasks",
    "dashboard.activeProjectsCount": "{count} active projects",
    "dashboard.nextDeadline": "next {date}",
    "dashboard.noDeadline": "no deadline",
    "dashboard.planNotSet": "Plan not set",
    "dashboard.noTraceableClientHealthIssues": "No traceable client health issues",
    "dashboard.noActiveClientWork": "No active client work yet",
    "dashboard.noActiveClientWorkHint": "Apply an agency template or create a client campaign to start tracking delivery.",
    "dashboard.internalOperation": "Internal operation",
    "dashboard.noCreativeQueue": "No creative queue yet",
    "dashboard.noCreativeQueueHint": "Use Creative, Production, or Marketing task templates to make creative deliverables visible here.",
    "dashboard.noDepartmentWorkload": "No department workload yet",
    "dashboard.noDepartmentWorkloadHint": "Assign members to departments and tasks to members to populate this view.",
    "dashboard.membersCount": "{count} members",
    "dashboard.dueSoonCount": "{count} due soon",
    "dashboard.noAgencyRiskSignals": "No agency risk signals yet",
    "dashboard.noAgencyRiskSignalsHint": "Traceable operational risk appears after tasks, clients, projects, owners, and activity records exist.",
    "dashboard.noMatchingActivity": "No matching activity.",
    "dashboard.all": "All",
    "dashboard.done": "Done",
    "dashboard.active": "Active",
    "dashboard.completedStatus": "Completed",
    "dashboard.inProgressStatus": "In progress",
    "dashboard.allActivityComingSoon": "All activity view coming soon",
    "dashboard.timeTrackingOptions": "Time tracking options",
    "dashboard.resetTimer": "Reset timer",
    "dashboard.switchProject": "Switch project",
    "dashboard.startTimer": "Start timer",
    "dashboard.stopTimer": "Stop timer",
    "dashboard.pauseTimer": "Pause timer",
    "dashboard.start": "Start",
    "dashboard.stop": "Stop",
    "dashboard.pause": "Pause",
    "dashboard.recentSplits": "Recent splits",
    "dashboard.todayMeetings": "Today meetings",
    "dashboard.clientHealthOverview": "Client health overview",
    "dashboard.deliveryOverview": "Campaign delivery overview",
    "dashboard.creativeProductionQueue": "Creative production queue",
    "dashboard.workloadByDepartment": "Workload by department",
    "dashboard.agencyRiskSignals": "Agency risk signals",
    "dashboard.closeCommandDrawer": "Close command drawer",
    "dashboard.noUrgentActions": "No urgent actions",
    "dashboard.noUrgentActionsHint": "Due, overdue, and high-priority assigned tasks appear here.",
    "dashboard.view": "View",
    "dashboard.manage": "Manage",
    "dashboard.viewAll": "View all",
    "dashboard.lastWeek": "Last week",
    "dashboard.clear": "Clear",
    "dashboard.hoursTasks": "{hours}h - {tasks} tasks",
    "dashboard.lastActions": "Last actions",
    "dashboard.todayFocus": "Today focus",
    "dashboard.todayFocusHint": "The shortest list of work that needs attention now.",
    "dashboard.noFocus": "No urgent focus items right now.",
    "dashboard.taskCreated": "Deliverable created",
    "dashboard.projectCreated": "Project created",
    "dashboard.taskDeleted": "Task deleted",
    "dashboard.couldNotDeleteTask": "Could not delete task",
    "dashboard.couldNotUpdateTask": "Could not update task",
    "dashboard.taskMoved": "Task moved to {status}",
    "dashboard.filtering": "Filtering",
    "dashboard.deleteEventConfirm": "Delete \"{title}\"?",
    "dashboard.noEventPermission": "You do not have permission to manage this event",
    "dashboard.meetingDeleteFailed": "Failed to delete meeting",
    "dashboard.meetingDeleted": "Meeting deleted",
    "dashboard.couldNotDeleteMeeting": "Could not delete meeting",
    "dashboard.titleRequired": "Title is required",
    "dashboard.meetingUpdateFailed": "Failed to update meeting",
    "dashboard.meetingUpdated": "Meeting updated",
    "dashboard.couldNotUpdateMeeting": "Could not update meeting",
    "dashboard.manageMeeting": "Manage meeting",
    "dashboard.manageEvent": "Manage event",
    "dashboard.titleField": "Title",
    "dashboard.timeField": "Time",
    "dashboard.locationField": "Location",
    "dashboard.deleteMeeting": "Delete meeting",
    "dashboard.timerStarted": "Timer started",
    "dashboard.timerStopped": "Timer stopped",
    "dashboard.couldNotStartTimer": "Could not start timer",
    "dashboard.couldNotStopTimer": "Could not stop timer",
    "dashboard.pauseUnavailable": "Pause is not available for persisted timers yet",
    "dashboard.switchedProject": "Switched to {project}",
    "dashboard.agencyOperations": "Agency operations",
    "dashboard.agencyOperationsTitle": "Client work, delivery, creative queue, and workload",
    "dashboard.agencyOperationsHint": "Built from real clients, campaigns, deliverables, deadlines, owners, activity, and time records.",
    "dashboard.traceRisks": "Trace risks",
    "dashboard.clientHealth": "Client health",
    "dashboard.healthyCount": "{count} healthy",
    "dashboard.needAttentionCount": "{count} need attention",
    "dashboard.addClientDataHint": "Add clients, projects, contacts, and activity",
    "dashboard.campaignDelivery": "Campaign delivery",
    "dashboard.activeCount": "{count} active",
    "dashboard.progressAndDeadlines": "Progress and next deadlines",
    "dashboard.creativeQueue": "Creative queue",
    "dashboard.deliverablesCount": "{count} deliverables",
    "dashboard.creativeSignalsHint": "Briefing, production, approval signals",
    "dashboard.noCreativeMatched": "No creative tasks matched yet",
    "dashboard.closestDeliveryDeadlines": "Closest delivery deadlines",
    "dashboard.applyAgencyTemplateHint": "No active client work yet. Apply an agency template or create a client campaign.",
    "dashboard.viewQueue": "View queue",
    "dashboard.noCreativeQueueLong": "No creative/content deliverables matched yet. Use Creative, Production, or Marketing templates to populate this queue.",
    "dashboard.agencyRiskOnlyTraceable": "Only traceable signals from tasks, clients, projects, owners, and activity.",
    "dashboard.notEnoughRiskData": "Not enough risk data yet, or no current operational risks were detected from real records.",
    "dashboard.stageBriefing": "Briefing",
    "dashboard.stageReady": "Ready",
    "dashboard.stageProduction": "Production",
    "dashboard.stageApproval": "Approval",
    "dashboard.stageRevision": "Revision",
    "projects.project": "Project",
    "projects.newProject": "New Project",
    "projects.projectName": "Project name",
    "projects.projectNamePlaceholder": "e.g. Website Redesign",
    "projects.description": "Description",
    "projects.descriptionPlaceholder": "Brief description of the project...",
    "projects.dueDate": "Due date",
    "projects.createProject": "Create Project",
    "projects.failedCreate": "Failed to create project",
    "projects.backToProjects": "Back to Projects",
    "projects.docs": "Docs",
    "projects.addTask": "Add Task",
    "projects.tasksLabel": "{count} tasks",
    "projects.due": "Due {date}",
    "projects.doneProgress": "{progress}% done",
    "projects.failedToLoad": "Failed to load project",
    "toolbar.list": "List",
    "toolbar.board": "Board",
    "toolbar.searchTasks": "Search tasks...",
    "toolbar.filter": "Filter",
    "toolbar.group": "Group: {label}",
    "toolbar.sort": "Sort: {label}",
    "toolbar.showClosed": "Show closed",
    "toolbar.customFields": "Custom fields",
    "toolbar.columns": "Columns",
    "toolbar.priority": "Priority",
    "toolbar.assignee": "Assignee",
    "toolbar.status": "Status",
    "toolbar.dueDate": "Due date",
    "toolbar.manual": "Manual",
    "toolbar.title": "Title",
    "toolbar.created": "Created",
    "toolbar.clearFilters": "Clear filters",
    "toolbar.sortAscending": "Sort ascending",
    "toolbar.sortDescending": "Sort descending",
    "task.newTask": "New Task",
    "task.taskName": "Task name",
    "task.notesPlaceholder": "Add task notes, client context, or internal instructions...",
    "task.titleRequired": "Title is required",
    "task.createTask": "Create deliverable",
    "task.failedCreate": "Failed to create task",
    "task.clickCycleStatus": "Click to cycle status",
    "task.boardCoverImage": "Board cover image",
    "task.subtasks": "Subtasks",
    "task.addSubtasksLater": "Add subtasks after creating the task from its detail view.",
    "task.deleteConfirm": "Delete this task?",
    "task.deleteSubtaskConfirm": "Delete this subtask?",
    "task.failedDelete": "Failed to delete",
    "task.failedAddComment": "Failed to add comment",
    "task.failedAddReply": "Failed to add reply",
    "task.failedAddSubtask": "Failed to add subtask",
    "task.failedDeleteSubtask": "Failed to delete subtask",
    "task.failedUpdateSubtask": "Failed to update subtask",
    "task.descriptionBrief": "Description / brief",
    "task.structuredBrief": "Structured task brief",
    "task.descriptionPlaceholder": "Add a description...",
    "task.noSubtasks": "No subtasks yet",
    "task.addSubtask": "Add subtask",
    "task.comments": "Comments",
    "task.addComment": "Add a comment...",
    "task.reply": "Reply",
    "taskTemplate.type": "Task type",
    "taskTemplate.general.label": "General task",
    "taskTemplate.creative.label": "Creative / Design",
    "taskTemplate.b2b_marketing.label": "B2B Marketing",
    "taskTemplate.b2c_marketing.label": "B2C Marketing",
    "taskTemplate.commercial.label": "Commercial",
    "taskTemplate.finance.label": "Finance",
    "taskTemplate.production.label": "Production",
    "taskTemplate.technical_support.label": "Technical Support",
    "taskTemplate.admin.label": "General Admin",
    "taskTemplate.general.description": "Simple work item with flexible notes.",
    "taskTemplate.creative.description": "Asset production, design, and approval work.",
    "taskTemplate.b2b_marketing.description": "Lead generation, outbound, and account-based campaigns.",
    "taskTemplate.b2c_marketing.description": "Consumer campaigns, launches, ads, and content.",
    "taskTemplate.commercial.description": "Sales, proposals, contracts, follow-up, and commissions.",
    "taskTemplate.finance.description": "Invoices, payments, commissions, expenses, and cashflow.",
    "taskTemplate.production.description": "Shoots, editing, publishing, deliverables, and production handoffs.",
    "taskTemplate.technical_support.description": "Support tickets, bug reports, access issues, escalations, and resolution notes.",
    "taskTemplate.admin.description": "Internal operations, access, documents, suppliers, and approvals.",
    "time.title": "Time tracking",
    "time.thisWeek": "This week",
    "time.today": "Today",
    "time.dailyAverage": "Daily average",
    "time.weeklyHours": "Weekly hours",
    "time.savedEntriesHint": "Time tracked from saved entries",
    "time.byProject": "By project",
    "time.projectHint": "Time logged per project this week",
    "time.noProject": "No project",
    "time.noTrackedTime": "No tracked time this week.",
    "time.day.mon": "Mon",
    "time.day.tue": "Tue",
    "time.day.wed": "Wed",
    "time.day.thu": "Thu",
    "time.day.fri": "Fri",
    "time.day.sat": "Sat",
    "time.day.sun": "Sun",
    "calendar.title": "Calendar",
    "calendar.view": "View",
    "calendar.manage": "Manage",
    "calendar.newEvent": "New event",
    "calendar.today": "Today",
    "calendar.previousMonth": "Previous month",
    "calendar.nextMonth": "Next month",
    "calendar.newEventDate": "New event on this date",
    "calendar.events": "Events",
    "calendar.noEvents": "No events on this day.",
    "calendar.addEvent": "Add event",
    "calendar.dueTasks": "Due tasks",
    "calendar.noDueTasks": "Nothing due on this day.",
    "calendar.legend": "Legend",
    "calendar.legendEvent": "Calendar event",
    "calendar.legendHigh": "High priority task",
    "calendar.legendLow": "Low priority task",
    "calendar.more": "+{count} more",
    "calendar.deleteConfirm": "Delete \"{title}\"?",
    "calendar.noPermission": "You do not have permission to manage this event",
    "calendar.eventDeleted": "Event deleted",
    "calendar.couldNotDelete": "Could not delete event",
    "calendar.titleRequired": "Title is required",
    "calendar.eventUpdated": "Event updated",
    "calendar.couldNotUpdate": "Could not update event",
    "calendar.manageEvent": "Manage {type}",
    "calendar.meeting": "meeting",
    "calendar.event": "event",
    "calendar.fieldTitle": "Title",
    "calendar.fieldTime": "Time",
    "calendar.fieldLocation": "Location",
    "calendar.scheduleMeeting": "Schedule meeting",
    "calendar.titleAndTimeRequired": "Title and time are required",
    "calendar.meetingScheduled": "Meeting scheduled",
    "calendar.couldNotSchedule": "Could not schedule meeting",
    "calendar.titlePlaceholder": "e.g. Sprint review",
    "calendar.with": "With",
    "calendar.withPlaceholder": "Team / client",
    "calendar.tag": "Tag",
    "calendar.scheduling": "Scheduling...",
    "calendar.schedule": "Schedule",
    "clients.title": "Clients",
    "clients.subtitle": "Companies, contacts, linked work, meetings, notes, and activity.",
    "clients.newCompany": "New company",
    "clients.couldNotLoad": "Could not load clients",
    "clients.noClients": "No clients yet",
    "clients.noClientsHint": "Create the first company to link projects, tasks, meetings, and notes.",
    "clients.planNotSet": "Plan not set",
    "clients.serviceTypeNotSet": "Service type not set",
    "clients.noIncludedServices": "No included services listed",
    "clients.activeProjects": "Active projects",
    "clients.open": "Open",
    "clients.contract": "Contract",
    "clients.linkedTime": "Linked time",
    "clients.valuePerHour": "Value / hour",
    "clients.noTimeValue": "No time value",
    "clients.contacts": "{count} contacts",
    "clients.meetings": "{count} meetings",
    "clients.commission": "Commission {value}",
    "clients.tracked": "{value} tracked",
    "clients.owner": "Owner {name}",
    "clients.ownerNotAssigned": "not assigned",
    "clients.assignedTeam": "Assigned team",
    "clients.noAssignedTeam": "No linked owner or assignee records",
    "clients.noTraceableIssues": "No traceable client health issues from current records",
    "clients.noValue": "No value",
    "clients.nextDeadlineNotSet": "Next deadline not set",
    "clients.overdueSince": "Overdue since {date}",
    "clients.nextDeadline": "Next deadline {date}",
    "clients.noActivity": "No activity recorded",
    "clients.health.healthy": "Healthy",
    "clients.health.attention": "Needs attention",
    "clients.health.risk": "At risk",
    "clients.health.notEnough": "Not enough data",
    "team.title": "Team",
    "team.membersTitle": "Team Members",
    "team.memberCount": "{count} member",
    "team.memberCountPlural": "{count} members",
    "team.viewingWorkspace": "viewing {workspace}",
    "team.departmentCount": "{count} department",
    "team.departmentCountPlural": "{count} departments",
    "team.inviteUsers": "Invite users",
    "team.manageDepartments": "Manage departments",
    "team.searchMembers": "Search members...",
    "team.showEmptyGroups": "Show empty groups",
    "team.noMembers": "No team members yet",
    "team.noSearchMatches": "No members match \"{query}\"",
    "team.tryDifferentSearch": "Try a different name or email.",
    "team.pendingInvites": "Pending invites",
    "team.awaitingAcceptance": "{count} invites awaiting acceptance",
    "team.awaitingAcceptanceOne": "{count} invite awaiting acceptance",
    "team.resend": "Resend",
    "team.sending": "Sending...",
    "team.cancelInvite": "Cancel",
    "team.invitedBy": "invited by {name}",
    "team.memberUpdated": "Member updated",
    "team.memberRemoved": "Member removed",
    "team.couldNotLoad": "Could not load team members for this workspace",
    "team.couldNotUpdateDepartment": "Could not update department",
    "team.couldNotUpdateMember": "Could not update member",
    "team.couldNotRemoveMember": "Could not remove member",
    "team.removeConfirm": "Remove {name} from this workspace?",
    "team.inviteResent": "Invite re-sent to {email}",
    "team.inviteDeliveryNotConfirmed": "Invite email delivery was not confirmed",
    "team.couldNotResend": "Could not resend to {email}",
    "team.cancelInviteConfirm": "Cancel invite for {email}?",
    "team.inviteCanceled": "Invite canceled for {email}",
    "team.couldNotCancelInvite": "Could not cancel invite for {email}",
    "team.roleFor": "Role for {name}",
    "team.statusFor": "Status for {name}",
    "team.departmentFor": "Department for {name}",
    "team.removeMember": "Remove {name}",
    "team.sandboxTools": "Sandbox tester tools - super admin only",
    "team.testerInviteTitle": "Invite testers",
    "team.testerInviteDescriptionWithWorkspace": "Tester invites join {workspace}. Choose Member for normal testers or Admin for trusted testers.",
    "team.testerInviteDescriptionFallback": "Tester invites join the isolated test workspace. Choose Member or Admin.",
    "team.sendTesterInvites": "Send tester invites",
    "team.testerEmail": "Tester email",
    "team.name": "Name",
    "team.testerNamePlaceholder": "Tester name",
    "team.tempPassword": "Temporary password",
    "team.emailRequired": "Email is required",
    "team.passwordMin": "Password must be at least 8 characters",
    "team.couldNotCreateTester": "Could not create tester account",
    "team.testerAccountCreated": "Tester account created",
    "team.sendCredentialsManually": "Send these credentials manually through WhatsApp, Gmail, or Slack.",
    "team.copyCredentials": "Copy credentials",
    "team.addsAccessTo": "Adds access to {workspace}.",
    "team.isolatedTestWorkspace": "the isolated test workspace",
    "team.defaultTesterWorkspace": "UP Flow Test Workspace",
    "team.serviceRoleMissing": "Add SUPABASE_SERVICE_ROLE_KEY in Vercel and redeploy before using manual account creation.",
    "team.generatedCredentialText": "UP Flow test access\nURL: {url}\nWorkspace: {workspace}\nEmail: {email}\nPassword: {password}",
    "team.couldNotCreateDepartment": "Couldn't create department",
    "team.couldNotRenameDepartment": "Couldn't rename department",
    "team.couldNotUpdateDepartmentColor": "Couldn't update department color",
    "team.deleteDepartmentConfirm": "Delete \"{name}\"? Its members will become Unassigned.",
    "team.couldNotDeleteDepartment": "Couldn't delete department",
    "team.noDepartmentsYet": "No departments yet. Create one below.",
    "team.addDepartment": "Add department",
    "team.departmentPlaceholder": "e.g. Engineering",
    "team.departmentNameLabel": "Department name ({name})",
    "team.deleteDepartmentLabel": "Delete {name}",
    "team.colorLabel": "Color {color}",
    "invite.realUsersTitle": "Invite real users to Up Flow",
    "invite.emailReady": "Email ready",
    "invite.checkEmailSetup": "Check email setup",
    "invite.realUsersDescription": "Send official invitations for two clear paths: users can get their own UP Flow workspace, or they can join {workspace} and appear here as team members after accepting.",
    "invite.testerWorkspaceTitle": "Tester invite workspace",
    "invite.testerWorkspaceDescription": "Invite outside testers into an isolated workspace with demo clients, tasks, meetings, docs, and activity. They will not see real workspace data unless you invite them separately.",
    "invite.preparingWorkspace": "Preparing...",
    "invite.prepareWorkspace": "Prepare workspace",
    "invite.createTesterAccount": "Create tester account",
    "invite.resettingTester": "Resetting...",
    "invite.resetTester": "Reset tester",
    "invite.emailInvite": "Email invite",
    "invite.viewTesterMembers": "View tester members",
    "invite.thisWorkspace": "this workspace",
    "invite.sourceWorkspace": "Source workspace",
    "invite.currentWorkspace": "Current workspace",
    "invite.internalMembers": "Internal members",
    "invite.pendingInvites": "Pending invites",
    "invite.emailSetupReady": "Invite email setup is ready",
    "invite.emailSetupAttention": "Invite email setup needs attention",
    "invite.emailConfigured": "APP_URL, RESEND_API_KEY, and EMAIL_FROM are configured with a non-development sender.",
    "invite.emailBlocked": "Invites are blocked until Resend delivery is configured and accepted.",
    "invite.missing": "Missing: {keys}.",
    "invite.setVerifiedSender": "Set EMAIL_FROM to a verified Resend sender.",
    "invite.lastTest": "Last test {time}: {message}",
    "invite.testing": "Testing...",
    "invite.sendTest": "Send test",
    "invite.titleDefault": "Invite to team",
    "invite.descriptionDefault": "We'll email each address an invitation link.",
    "invite.submitDefault": "Send invites",
    "invite.successDefault": "Invited",
    "invite.emailLabel": "Emails (comma or newline separated)",
    "invite.addAtLeastOne": "Add at least one email",
    "invite.couldNotSend": "Could not send invites",
    "invite.deliveryNotConfirmed": "Invite email delivery was not confirmed",
    "invite.teammate": "teammate",
    "invite.teammates": "teammates",
    "invite.mode": "Invite mode",
    "invite.ownWorkspace": "Own workspace",
    "invite.workspaceAccess": "This workspace",
    "invite.workspaceModeHint": "They join this workspace and appear as team members after accepting.",
    "invite.personalModeHint": "They get their own UP Flow workspace and do not see this workspace.",
    "invite.role": "Role",
    "invite.appUrlMissing": "Set APP_URL to the canonical public app URL and restart the app.",
    "invite.emailNotConfigured": "Set RESEND_API_KEY and EMAIL_FROM with a verified Resend sender, then restart the app.",
    "invite.emailSendFailed": "Check the Resend dashboard, API key, sender verification, recipient restrictions, and provider message.",
    "invite.checkSetup": "Check invite email setup and try again.",
    "invite.notFound": "Invite not found",
    "invite.loadFailed": "Failed to load invite",
    "invite.acceptFailed": "Could not accept invite",
    "invite.signInFailed": "Could not sign in with that password.",
    "invite.signInAcceptFailed": "Signed in, but could not accept invite.",
    "invite.accountExists": "Account already exists. Sign in to accept.",
    "invite.createAccountFailed": "Could not create account",
    "invite.createAccount": "Create account",
    "invite.pageTitle": "You've been invited",
    "invite.loading": "Loading invite...",
    "invite.testerBadge": "Tester workspace",
    "invite.workspaceAccessBadge": "Workspace access",
    "invite.invitedBy": "{name} invited you to use",
    "invite.someone": "Someone",
    "invite.productName": "Up Flow",
    "invite.inviteFor": "Invite for",
    "invite.testerExplanation": "This invite opens an isolated UP Flow test workspace with demo projects, clients, meetings, docs, and tasks. It does not grant access to real client workspaces.",
    "invite.workspaceAccessExplanation": "This invite adds you to {workspace}. After accepting, you will appear as a team member and can work with real workspace projects, tasks, calendar events, and clients.",
    "invite.personalWorkspaceExplanation": "This invite creates your own UP Flow workspace so you can use the platform without receiving access to {workspace}.",
    "invite.email": "Email",
    "invite.fullName": "Full name",
    "invite.fullNamePlaceholder": "Your full name",
    "invite.cellphone": "Cellphone number",
    "invite.password": "Password",
    "invite.passwordPlaceholder": "Minimum 8 characters",
    "invite.enterPassword": "Enter your password",
    "invite.creating": "Creating...",
    "invite.createAndOpen": "Create account and open workspace",
    "invite.signingIn": "Signing in...",
    "invite.signIn": "Sign in",
    "invite.signInAndOpen": "Sign in and open workspace",
    "invite.alreadySignedIn": "I am already signed in",
    "invite.fullLoginPrompt": "Need the full login page?",
    "invite.openSignIn": "Open sign in",
    "error.pageTitle": "This page could not load",
    "error.pageBody": "The app could not finish loading this screen. Try again first. If it keeps happening, go back to the dashboard and check Admin Health for database, Supabase, or email configuration issues.",
    "error.reference": "Reference",
    "error.retryPage": "Retry page",
    "error.openDashboard": "Open dashboard",
    "error.notFoundTitle": "Page not found",
    "error.notFoundBody": "The page you were looking for does not exist or has been moved.",
    "error.backDashboard": "Back to dashboard",
  },
  "pt-BR": {
    "language.english": "Inglês",
    "language.portugueseBrazil": "Português (Brasil)",
    "language.shortEnglish": "EN",
    "language.shortPortuguese": "PT-BR",
    "language.toggle": "Alterar idioma",
    "header.searchPlaceholder": "Buscar {title}, projetos, tarefas, docs...",
    "header.notifications": "Notificacoes",
    "header.markAllRead": "Marcar tudo como lido",
    "header.allCaughtUp": "Tudo em dia",
    "header.newProject": "Novo projeto",
    "nav.dashboard": "Dashboard",
    "nav.team": "Equipe",
    "nav.timeTracking": "Controle de tempo",
    "nav.inbox": "Caixa de entrada",
    "nav.calendar": "Calendário",
    "nav.projects": "Projetos",
    "nav.clients": "Clientes",
    "sidebar.show": "Mostrar sidebar",
    "sidebar.hide": "Ocultar sidebar",
    "sidebar.help": "Ajuda",
    "sidebar.signOut": "Sair",
    "sidebar.navigation": "Navegação",
    "sidebar.workspace": "Workspace",
    "sidebar.spaces": "Espaços",
    "sidebar.collapseAll": "Recolher tudo",
    "sidebar.newSpace": "Novo espaço",
    "sidebar.searchSpaces": "Buscar espaços...",
    "sidebar.clearSearch": "Limpar busca da sidebar",
    "sidebar.loading": "Carregando...",
    "sidebar.noSearchMatches": "Nenhum espaço, pasta ou lista corresponde a {query}.",
    "sidebar.noSpaces": "Nenhum espaço ainda.",
    "sidebar.createFirstSpace": "Criar primeiro espaço",
    "workspace.loading": "Carregando workspace...",
    "workspace.namePrompt": "Nome do workspace",
    "workspace.switchError": "Não foi possível trocar de workspace",
    "workspace.createError": "Não foi possível criar workspace",
    "workspace.new": "Novo workspace",
    "auth.signedOut": "Sessão encerrada",
    "auth.signOutFailed": "Falha ao sair; tente novamente",
    "common.cancel": "Cancelar",
    "common.create": "Criar",
    "common.delete": "Excluir",
    "common.open": "Abrir",
    "common.updated": "Atualizado",
    "common.failedToUpdate": "Falha ao atualizar",
    "common.none": "Nenhum",
    "common.anyone": "Qualquer pessoa",
    "common.unassigned": "Sem responsável",
    "common.creating": "Criando...",
    "common.loading": "Carregando...",
    "common.retry": "Tentar novamente",
    "common.refresh": "Atualizar",
    "common.save": "Salvar",
    "common.saving": "Salvando...",
    "common.close": "Fechar",
    "common.done": "Concluído",
    "common.add": "Adicionar",
    "common.generate": "Gerar",
    "common.member": "Membro",
    "common.admin": "Admin",
    "common.owner": "Dono",
    "common.active": "Ativo",
    "common.inactive": "Inativo",
    "common.sent": "enviado",
    "common.accepted": "aceito",
    "common.failed": "falhou",
    "common.selected": "Selecionado",
    "status.todo": "A fazer",
    "status.inProgress": "Em andamento",
    "status.done": "Concluído",
    "priority.low": "Baixa",
    "priority.medium": "Média",
    "priority.high": "Alta",
    "dashboard.title": "Dashboard",
    "dashboard.commandCenter": "Centro de Operações da Agência",
    "dashboard.good": "{greeting}, {name}",
    "dashboard.hi": "Olá, {name}",
    "dashboard.greeting.morning": "Bom dia",
    "dashboard.greeting.afternoon": "Boa tarde",
    "dashboard.greeting.evening": "Boa noite",
    "dashboard.summary": "Clientes, campanhas, entregas, reuniões, tempo, riscos, carga da equipe e receita em uma visão operacional.",
    "dashboard.risks": "{count} riscos",
    "dashboard.tasksComplete": "{progress}% das entregas concluídas",
    "dashboard.timerRunning": "Timer em andamento",
    "dashboard.noActiveTimer": "Nenhum timer ativo",
    "dashboard.operationalPulse": "Pulso operacional",
    "dashboard.nextMeeting": "Próxima reunião",
    "dashboard.noneToday": "Nenhuma hoje",
    "dashboard.focusQueue": "Fila de foco",
    "dashboard.items": "{count} itens",
    "dashboard.quickCreate": "Criação rápida",
    "dashboard.openWork": "Trabalho aberto",
    "dashboard.tasksCount": "{count} entregas",
    "dashboard.tasks": "Entregas",
    "dashboard.teamFlags": "Alertas da equipe",
    "dashboard.lateOrOverloaded": "Atrasadas ou 8+ tarefas abertas",
    "dashboard.activity": "Atividade",
    "dashboard.workspaceTrail": "Histórico do workspace",
    "dashboard.myUrgentActions": "Tarefas urgentes atribuídas",
    "dashboard.urgentHint": "Para hoje, atrasadas ou entregas de alta prioridade",
    "dashboard.meetingsToday": "Reuniões de hoje",
    "dashboard.meetingsHint": "Eventos agendados para hoje",
    "dashboard.timeToday": "Tempo hoje",
    "dashboard.trackedToday": "Entradas registradas hoje",
    "dashboard.projectsAtRisk": "Campanhas em risco",
    "dashboard.projectsRiskHint": "Tarefas atrasadas ou sem atividade em 7 dias",
    "dashboard.clientRisk": "Risco de clientes",
    "dashboard.clientRiskHint": "Clientes com atrasos, configuração incompleta ou sem atividade recente",
    "dashboard.revenueSnapshot": "Resumo de receita",
    "dashboard.activeClients": "{count} clientes ativos",
    "dashboard.statusHint": "Status de entrega fica a um clique dos registros exatos.",
    "dashboard.newTask": "Nova entrega",
    "dashboard.completion": "Conclusão",
    "dashboard.upcoming": "Pendentes",
    "dashboard.upcomingHint": "Entregas aguardando início",
    "dashboard.inProgress": "Em andamento",
    "dashboard.inProgressHint": "Em execução agora",
    "dashboard.completed": "Concluídas",
    "dashboard.ofTotal": "{progress}% do total",
    "dashboard.teamWorkload": "Carga da equipe",
    "dashboard.membersWithSignals": "{count} membros com sinais",
    "dashboard.recentActivity": "Atividade recente",
    "dashboard.traceableRecords": "{count} registros rastreáveis",
    "dashboard.noRecentActivity": "Nenhuma atividade recente",
    "dashboard.noRecentActivityHint": "Operações importantes do workspace aparecerão aqui.",
    "dashboard.noTrackedTime": "Nenhum tempo registrado hoje",
    "dashboard.noTrackedTimeHint": "Inicie um timer para criar a primeira entrada real de tempo.",
    "dashboard.totalToday": "Total de hoje",
    "dashboard.trackedTimeFallback": "Tempo registrado",
    "dashboard.running": "em andamento",
    "dashboard.logged": "registrado",
    "dashboard.noMeetings": "Nenhuma reunião hoje",
    "dashboard.noMeetingsHint": "Eventos de calendário criados neste workspace aparecerão aqui.",
    "dashboard.addMeeting": "Adicionar reunião",
    "dashboard.noProjectsAtRisk": "Nenhum projeto em risco",
    "dashboard.noProjectsAtRiskHint": "As regras de risco verificam tarefas atrasadas e falta de atividade recente.",
    "dashboard.noClientsAtRisk": "Nenhum cliente em risco",
    "dashboard.noClientsAtRiskHint": "O risco de cliente verifica projetos vinculados, contatos, trabalho atrasado, valor de contrato e atividade recente.",
    "dashboard.notEnoughClientData": "Ainda não há dados suficientes de clientes",
    "dashboard.notEnoughClientDataHint": "A saúde do cliente aparece depois que houver trabalho vinculado, contatos, plano ou atividade.",
    "dashboard.noProject": "Sem projeto",
    "dashboard.due": "vence {date}",
    "dashboard.noWorkloadTasks": "Nenhuma tarefa aberta atribuída por trás deste sinal de carga.",
    "dashboard.overdueCount": "{count} atrasadas",
    "dashboard.openTasksCount": "{count} tarefas abertas",
    "dashboard.activeProjectsCount": "{count} projetos ativos",
    "dashboard.nextDeadline": "próximo {date}",
    "dashboard.noDeadline": "sem prazo",
    "dashboard.planNotSet": "Plano não definido",
    "dashboard.noTraceableClientHealthIssues": "Nenhum problema rastreável de saúde do cliente",
    "dashboard.noActiveClientWork": "Nenhum trabalho ativo de cliente ainda",
    "dashboard.noActiveClientWorkHint": "Aplique um template da agência ou crie uma campanha de cliente para começar a acompanhar a entrega.",
    "dashboard.internalOperation": "Operação interna",
    "dashboard.noCreativeQueue": "Nenhuma fila criativa ainda",
    "dashboard.noCreativeQueueHint": "Use templates de Criação, Produção ou Marketing para mostrar entregas criativas aqui.",
    "dashboard.noDepartmentWorkload": "Nenhuma carga por departamento ainda",
    "dashboard.noDepartmentWorkloadHint": "Atribua membros aos departamentos e tarefas aos membros para preencher esta visão.",
    "dashboard.membersCount": "{count} membros",
    "dashboard.dueSoonCount": "{count} próximas",
    "dashboard.noAgencyRiskSignals": "Nenhum sinal de risco da agência ainda",
    "dashboard.noAgencyRiskSignalsHint": "Riscos operacionais rastreáveis aparecem depois que tarefas, clientes, projetos, responsáveis e atividades existirem.",
    "dashboard.noMatchingActivity": "Nenhuma atividade correspondente.",
    "dashboard.all": "Todos",
    "dashboard.done": "Concluídas",
    "dashboard.active": "Ativas",
    "dashboard.completedStatus": "Concluído",
    "dashboard.inProgressStatus": "Em andamento",
    "dashboard.allActivityComingSoon": "Visão completa de atividade em breve",
    "dashboard.timeTrackingOptions": "Opções de controle de tempo",
    "dashboard.resetTimer": "Resetar timer",
    "dashboard.switchProject": "Trocar projeto",
    "dashboard.startTimer": "Iniciar timer",
    "dashboard.stopTimer": "Parar timer",
    "dashboard.pauseTimer": "Pausar timer",
    "dashboard.start": "Iniciar",
    "dashboard.stop": "Parar",
    "dashboard.pause": "Pausar",
    "dashboard.recentSplits": "Divisões recentes",
    "dashboard.todayMeetings": "Reuniões de hoje",
    "dashboard.clientHealthOverview": "Visão de saúde dos clientes",
    "dashboard.deliveryOverview": "Visão de entrega das campanhas",
    "dashboard.creativeProductionQueue": "Fila de produção criativa",
    "dashboard.workloadByDepartment": "Carga por departamento",
    "dashboard.agencyRiskSignals": "Sinais de risco da agência",
    "dashboard.closeCommandDrawer": "Fechar painel de comando",
    "dashboard.noUrgentActions": "Nenhuma ação urgente",
    "dashboard.noUrgentActionsHint": "Tarefas atribuídas para hoje, atrasadas e de alta prioridade aparecem aqui.",
    "dashboard.view": "Visualizar",
    "dashboard.manage": "Gerenciar",
    "dashboard.viewAll": "Ver tudo",
    "dashboard.lastWeek": "Última semana",
    "dashboard.clear": "Limpar",
    "dashboard.hoursTasks": "{hours}h - {tasks} tarefas",
    "dashboard.lastActions": "Últimas ações",
    "dashboard.todayFocus": "Foco de hoje",
    "dashboard.todayFocusHint": "A lista mais curta do que precisa de atenção agora.",
    "dashboard.noFocus": "Nenhum item urgente agora.",
    "dashboard.taskCreated": "Entrega criada",
    "dashboard.projectCreated": "Projeto criado",
    "dashboard.taskDeleted": "Tarefa excluída",
    "dashboard.couldNotDeleteTask": "Não foi possível excluir a tarefa",
    "dashboard.couldNotUpdateTask": "Não foi possível atualizar a tarefa",
    "dashboard.taskMoved": "Tarefa movida para {status}",
    "dashboard.filtering": "Filtrando",
    "dashboard.deleteEventConfirm": "Excluir \"{title}\"?",
    "dashboard.noEventPermission": "Você não tem permissão para gerenciar este evento",
    "dashboard.meetingDeleteFailed": "Falha ao excluir reunião",
    "dashboard.meetingDeleted": "Reunião excluída",
    "dashboard.couldNotDeleteMeeting": "Não foi possível excluir a reunião",
    "dashboard.titleRequired": "Título é obrigatório",
    "dashboard.meetingUpdateFailed": "Falha ao atualizar reunião",
    "dashboard.meetingUpdated": "Reunião atualizada",
    "dashboard.couldNotUpdateMeeting": "Não foi possível atualizar a reunião",
    "dashboard.manageMeeting": "Gerenciar reunião",
    "dashboard.manageEvent": "Gerenciar evento",
    "dashboard.titleField": "Título",
    "dashboard.timeField": "Horário",
    "dashboard.locationField": "Local",
    "dashboard.deleteMeeting": "Excluir reunião",
    "dashboard.timerStarted": "Timer iniciado",
    "dashboard.timerStopped": "Timer parado",
    "dashboard.couldNotStartTimer": "Não foi possível iniciar o timer",
    "dashboard.couldNotStopTimer": "Não foi possível parar o timer",
    "dashboard.pauseUnavailable": "A pausa ainda não está disponível para timers persistidos",
    "dashboard.switchedProject": "Alterado para {project}",
    "dashboard.agencyOperations": "Operações da agência",
    "dashboard.agencyOperationsTitle": "Clientes, entregas, fila criativa e carga de trabalho",
    "dashboard.agencyOperationsHint": "Construído com clientes, campanhas, entregas, prazos, responsáveis, atividades e tempo reais.",
    "dashboard.traceRisks": "Rastrear riscos",
    "dashboard.clientHealth": "Saúde dos clientes",
    "dashboard.healthyCount": "{count} saudáveis",
    "dashboard.needAttentionCount": "{count} precisam de atenção",
    "dashboard.addClientDataHint": "Adicione clientes, projetos, contatos e atividades",
    "dashboard.campaignDelivery": "Entrega de campanhas",
    "dashboard.activeCount": "{count} ativos",
    "dashboard.progressAndDeadlines": "Progresso e próximos prazos",
    "dashboard.creativeQueue": "Fila criativa",
    "dashboard.deliverablesCount": "{count} entregas",
    "dashboard.creativeSignalsHint": "Sinais de briefing, produção e aprovação",
    "dashboard.noCreativeMatched": "Nenhuma tarefa criativa encontrada ainda",
    "dashboard.closestDeliveryDeadlines": "Prazos de entrega mais próximos",
    "dashboard.applyAgencyTemplateHint": "Nenhum trabalho ativo de cliente ainda. Aplique um template da agência ou crie uma campanha de cliente.",
    "dashboard.viewQueue": "Ver fila",
    "dashboard.noCreativeQueueLong": "Nenhuma entrega criativa ou de conteúdo encontrada ainda. Use templates de Criativo, Produção ou Marketing para preencher esta fila.",
    "dashboard.agencyRiskOnlyTraceable": "Somente sinais rastreáveis de tarefas, clientes, projetos, responsáveis e atividade.",
    "dashboard.notEnoughRiskData": "Ainda não há dados de risco suficientes, ou nenhum risco operacional atual foi detectado nos registros reais.",
    "dashboard.stageBriefing": "Briefing",
    "dashboard.stageReady": "Pronto",
    "dashboard.stageProduction": "Produção",
    "dashboard.stageApproval": "Aprovação",
    "dashboard.stageRevision": "Revisão",
    "projects.project": "Projeto",
    "projects.newProject": "Novo projeto",
    "projects.projectName": "Nome do projeto",
    "projects.projectNamePlaceholder": "ex.: Redesign do site",
    "projects.description": "Descrição",
    "projects.descriptionPlaceholder": "Breve descrição do projeto...",
    "projects.dueDate": "Data de vencimento",
    "projects.createProject": "Criar projeto",
    "projects.failedCreate": "Falha ao criar projeto",
    "projects.backToProjects": "Voltar para Projetos",
    "projects.docs": "Docs",
    "projects.addTask": "Adicionar tarefa",
    "projects.tasksLabel": "{count} tarefas",
    "projects.due": "Vence em {date}",
    "projects.doneProgress": "{progress}% concluído",
    "projects.failedToLoad": "Falha ao carregar projeto",
    "toolbar.list": "Lista",
    "toolbar.board": "Quadro",
    "toolbar.searchTasks": "Buscar tarefas...",
    "toolbar.filter": "Filtro",
    "toolbar.group": "Grupo: {label}",
    "toolbar.sort": "Ordenar: {label}",
    "toolbar.showClosed": "Mostrar concluídas",
    "toolbar.customFields": "Campos personalizados",
    "toolbar.columns": "Colunas",
    "toolbar.priority": "Prioridade",
    "toolbar.assignee": "Responsável",
    "toolbar.status": "Status",
    "toolbar.dueDate": "Data de vencimento",
    "toolbar.manual": "Manual",
    "toolbar.title": "Título",
    "toolbar.created": "Criado",
    "toolbar.clearFilters": "Limpar filtros",
    "toolbar.sortAscending": "Ordenar crescente",
    "toolbar.sortDescending": "Ordenar decrescente",
    "task.newTask": "Nova tarefa",
    "task.taskName": "Nome da tarefa",
    "task.notesPlaceholder": "Adicione notas, contexto do cliente ou instruções internas...",
    "task.titleRequired": "Título é obrigatório",
    "task.createTask": "Criar entrega",
    "task.failedCreate": "Falha ao criar tarefa",
    "task.clickCycleStatus": "Clique para alternar status",
    "task.boardCoverImage": "Imagem de capa no quadro",
    "task.subtasks": "Subtarefas",
    "task.addSubtasksLater": "Adicione subtarefas depois de criar a tarefa pela tela de detalhes.",
    "task.deleteConfirm": "Excluir esta tarefa?",
    "task.deleteSubtaskConfirm": "Excluir esta subtarefa?",
    "task.failedDelete": "Falha ao excluir",
    "task.failedAddComment": "Falha ao adicionar comentário",
    "task.failedAddReply": "Falha ao adicionar resposta",
    "task.failedAddSubtask": "Falha ao adicionar subtarefa",
    "task.failedDeleteSubtask": "Falha ao excluir subtarefa",
    "task.failedUpdateSubtask": "Falha ao atualizar subtarefa",
    "task.descriptionBrief": "Descrição / briefing",
    "task.structuredBrief": "Briefing estruturado",
    "task.descriptionPlaceholder": "Adicione uma descrição...",
    "task.noSubtasks": "Nenhuma subtarefa ainda",
    "task.addSubtask": "Adicionar subtarefa",
    "task.comments": "Comentários",
    "task.addComment": "Adicionar comentário...",
    "task.reply": "Responder",
    "taskTemplate.type": "Tipo de tarefa",
    "taskTemplate.general.label": "Tarefa geral",
    "taskTemplate.creative.label": "Criativo / Design",
    "taskTemplate.b2b_marketing.label": "Marketing B2B",
    "taskTemplate.b2c_marketing.label": "Marketing B2C",
    "taskTemplate.commercial.label": "Comercial",
    "taskTemplate.finance.label": "Financeiro",
    "taskTemplate.production.label": "Produção",
    "taskTemplate.technical_support.label": "Suporte técnico",
    "taskTemplate.admin.label": "Administrativo geral",
    "taskTemplate.general.description": "Item simples de trabalho com notas flexíveis.",
    "taskTemplate.creative.description": "Produção de assets, design e aprovações.",
    "taskTemplate.b2b_marketing.description": "Geração de leads, outbound e campanhas por conta.",
    "taskTemplate.b2c_marketing.description": "Campanhas de consumo, lançamentos, anúncios e conteúdo.",
    "taskTemplate.commercial.description": "Vendas, propostas, contratos, follow-up e comissões.",
    "taskTemplate.finance.description": "Notas, pagamentos, comissões, despesas e caixa.",
    "taskTemplate.production.description": "Gravações, edição, publicação, entregáveis e repasses de produção.",
    "taskTemplate.technical_support.description": "Tickets de suporte, bugs, acessos, escalações e notas de resolução.",
    "taskTemplate.admin.description": "Operações internas, acessos, documentos, fornecedores e aprovações.",
    "time.title": "Controle de tempo",
    "time.thisWeek": "Esta semana",
    "time.today": "Hoje",
    "time.dailyAverage": "Média diária",
    "time.weeklyHours": "Horas da semana",
    "time.savedEntriesHint": "Tempo registrado a partir de entradas salvas",
    "time.byProject": "Por projeto",
    "time.projectHint": "Tempo registrado por projeto nesta semana",
    "time.noProject": "Sem projeto",
    "time.noTrackedTime": "Nenhum tempo registrado nesta semana.",
    "time.day.mon": "Seg",
    "time.day.tue": "Ter",
    "time.day.wed": "Qua",
    "time.day.thu": "Qui",
    "time.day.fri": "Sex",
    "time.day.sat": "Sab",
    "time.day.sun": "Dom",
    "calendar.title": "Calendário",
    "calendar.view": "Visualizar",
    "calendar.manage": "Gerenciar",
    "calendar.newEvent": "Novo evento",
    "calendar.today": "Hoje",
    "calendar.previousMonth": "Mês anterior",
    "calendar.nextMonth": "Próximo mês",
    "calendar.newEventDate": "Novo evento nesta data",
    "calendar.events": "Eventos",
    "calendar.noEvents": "Nenhum evento neste dia.",
    "calendar.addEvent": "Adicionar evento",
    "calendar.dueTasks": "Tarefas com prazo",
    "calendar.noDueTasks": "Nada vence neste dia.",
    "calendar.legend": "Legenda",
    "calendar.legendEvent": "Evento do calendário",
    "calendar.legendHigh": "Tarefa de alta prioridade",
    "calendar.legendLow": "Tarefa de baixa prioridade",
    "calendar.more": "+{count} mais",
    "calendar.deleteConfirm": "Excluir \"{title}\"?",
    "calendar.noPermission": "Você não tem permissão para gerenciar este evento",
    "calendar.eventDeleted": "Evento excluido",
    "calendar.couldNotDelete": "Não foi possível excluir o evento",
    "calendar.titleRequired": "Título é obrigatório",
    "calendar.eventUpdated": "Evento atualizado",
    "calendar.couldNotUpdate": "Não foi possível atualizar o evento",
    "calendar.manageEvent": "Gerenciar {type}",
    "calendar.meeting": "reunião",
    "calendar.event": "evento",
    "calendar.fieldTitle": "Título",
    "calendar.fieldTime": "Horário",
    "calendar.fieldLocation": "Local",
    "calendar.scheduleMeeting": "Agendar reunião",
    "calendar.titleAndTimeRequired": "Título e horário são obrigatórios",
    "calendar.meetingScheduled": "Reunião agendada",
    "calendar.couldNotSchedule": "Não foi possível agendar a reunião",
    "calendar.titlePlaceholder": "ex.: Revisão de sprint",
    "calendar.with": "Com",
    "calendar.withPlaceholder": "Equipe / cliente",
    "calendar.tag": "Etiqueta",
    "calendar.scheduling": "Agendando...",
    "calendar.schedule": "Agendar",
    "clients.title": "Clientes",
    "clients.subtitle": "Empresas, contatos, trabalho vinculado, reuniões, notas e atividade.",
    "clients.newCompany": "Nova empresa",
    "clients.couldNotLoad": "Não foi possível carregar clientes",
    "clients.noClients": "Nenhum cliente ainda",
    "clients.noClientsHint": "Crie a primeira empresa para vincular projetos, tarefas, reuniões e notas.",
    "clients.planNotSet": "Plano não definido",
    "clients.serviceTypeNotSet": "Tipo de serviço não definido",
    "clients.noIncludedServices": "Nenhum serviço incluído listado",
    "clients.activeProjects": "Projetos ativos",
    "clients.open": "Abertas",
    "clients.contract": "Contrato",
    "clients.linkedTime": "Tempo vinculado",
    "clients.valuePerHour": "Valor / hora",
    "clients.noTimeValue": "Sem valor de tempo",
    "clients.contacts": "{count} contatos",
    "clients.meetings": "{count} reuniões",
    "clients.commission": "Comissão {value}",
    "clients.tracked": "{value} registrado",
    "clients.owner": "Responsável {name}",
    "clients.ownerNotAssigned": "não atribuído",
    "clients.assignedTeam": "Equipe atribuída",
    "clients.noAssignedTeam": "Nenhum responsável ou registro de atribuição vinculado",
    "clients.noTraceableIssues": "Nenhum problema rastreável de saúde do cliente nos registros atuais",
    "clients.noValue": "Sem valor",
    "clients.nextDeadlineNotSet": "Próximo prazo não definido",
    "clients.overdueSince": "Atrasado desde {date}",
    "clients.nextDeadline": "Próximo prazo {date}",
    "clients.noActivity": "Nenhuma atividade registrada",
    "clients.health.healthy": "Saudável",
    "clients.health.attention": "Precisa de atenção",
    "clients.health.risk": "Em risco",
    "clients.health.notEnough": "Dados insuficientes",
    "team.title": "Equipe",
    "team.membersTitle": "Membros da equipe",
    "team.memberCount": "{count} membro",
    "team.memberCountPlural": "{count} membros",
    "team.viewingWorkspace": "visualizando {workspace}",
    "team.departmentCount": "{count} departamento",
    "team.departmentCountPlural": "{count} departamentos",
    "team.inviteUsers": "Convidar usuários",
    "team.manageDepartments": "Gerenciar departamentos",
    "team.searchMembers": "Buscar membros...",
    "team.showEmptyGroups": "Mostrar grupos vazios",
    "team.noMembers": "Nenhum membro da equipe ainda",
    "team.noSearchMatches": "Nenhum membro corresponde a \"{query}\"",
    "team.tryDifferentSearch": "Tente outro nome ou email.",
    "team.pendingInvites": "Convites pendentes",
    "team.awaitingAcceptance": "{count} convites aguardando aceite",
    "team.awaitingAcceptanceOne": "{count} convite aguardando aceite",
    "team.resend": "Reenviar",
    "team.sending": "Enviando...",
    "team.cancelInvite": "Cancelar",
    "team.invitedBy": "convidado por {name}",
    "team.memberUpdated": "Membro atualizado",
    "team.memberRemoved": "Membro removido",
    "team.couldNotLoad": "Não foi possível carregar os membros desta workspace",
    "team.couldNotUpdateDepartment": "Não foi possível atualizar o departamento",
    "team.couldNotUpdateMember": "Não foi possível atualizar o membro",
    "team.couldNotRemoveMember": "Não foi possível remover o membro",
    "team.removeConfirm": "Remover {name} desta workspace?",
    "team.inviteResent": "Convite reenviado para {email}",
    "team.inviteDeliveryNotConfirmed": "A entrega do email de convite não foi confirmada",
    "team.couldNotResend": "Não foi possível reenviar para {email}",
    "team.cancelInviteConfirm": "Cancelar convite para {email}?",
    "team.inviteCanceled": "Convite cancelado para {email}",
    "team.couldNotCancelInvite": "Não foi possível cancelar o convite para {email}",
    "team.roleFor": "Função de {name}",
    "team.statusFor": "Status de {name}",
    "team.departmentFor": "Departamento de {name}",
    "team.removeMember": "Remover {name}",
    "team.sandboxTools": "Ferramentas sandbox de teste - somente super admin",
    "team.testerInviteTitle": "Convidar testadores",
    "team.testerInviteDescriptionWithWorkspace": "Convites de teste dão acesso a {workspace}. Escolha Membro para testadores comuns ou Admin para testadores confiáveis.",
    "team.testerInviteDescriptionFallback": "Convites de teste entram na workspace isolada de teste. Escolha Membro ou Admin.",
    "team.sendTesterInvites": "Enviar convites de teste",
    "team.testerEmail": "Email do testador",
    "team.name": "Nome",
    "team.testerNamePlaceholder": "Nome do testador",
    "team.tempPassword": "Senha temporária",
    "team.emailRequired": "Email é obrigatório",
    "team.passwordMin": "A senha deve ter pelo menos 8 caracteres",
    "team.couldNotCreateTester": "Não foi possível criar a conta de teste",
    "team.testerAccountCreated": "Conta de teste criada",
    "team.sendCredentialsManually": "Envie estas credenciais manualmente pelo WhatsApp, Gmail ou Slack.",
    "team.copyCredentials": "Copiar credenciais",
    "team.addsAccessTo": "Adiciona acesso a {workspace}.",
    "team.isolatedTestWorkspace": "a workspace isolada de teste",
    "team.defaultTesterWorkspace": "UP Flow Test Workspace",
    "team.serviceRoleMissing": "Adicione SUPABASE_SERVICE_ROLE_KEY na Vercel e faça o redeploy antes de usar a criação manual de conta.",
    "team.generatedCredentialText": "Acesso de teste UP Flow\nURL: {url}\nWorkspace: {workspace}\nEmail: {email}\nSenha: {password}",
    "team.couldNotCreateDepartment": "Não foi possível criar o departamento",
    "team.couldNotRenameDepartment": "Não foi possível renomear o departamento",
    "team.couldNotUpdateDepartmentColor": "Não foi possível atualizar a cor do departamento",
    "team.deleteDepartmentConfirm": "Excluir \"{name}\"? Os membros ficarão sem departamento.",
    "team.couldNotDeleteDepartment": "Não foi possível excluir o departamento",
    "team.noDepartmentsYet": "Nenhum departamento ainda. Crie um abaixo.",
    "team.addDepartment": "Adicionar departamento",
    "team.departmentPlaceholder": "ex. Engenharia",
    "team.departmentNameLabel": "Nome do departamento ({name})",
    "team.deleteDepartmentLabel": "Excluir {name}",
    "team.colorLabel": "Cor {color}",
    "invite.realUsersTitle": "Convidar usuários reais para o Up Flow",
    "invite.emailReady": "Email pronto",
    "invite.checkEmailSetup": "Verificar email",
    "invite.realUsersDescription": "Envie convites oficiais com dois caminhos claros: os usuários podem criar a própria workspace no UP Flow ou entrar em {workspace} e aparecer aqui como membros da equipe depois do aceite.",
    "invite.testerWorkspaceTitle": "Workspace de convites para teste",
    "invite.testerWorkspaceDescription": "Convide testadores externos para uma workspace isolada com clientes, tarefas, reuniões, documentos e atividades de exemplo. Eles não veem dados reais da workspace, a menos que você os convide separadamente.",
    "invite.preparingWorkspace": "Preparando...",
    "invite.prepareWorkspace": "Preparar workspace",
    "invite.createTesterAccount": "Criar conta de teste",
    "invite.resettingTester": "Resetando...",
    "invite.resetTester": "Resetar teste",
    "invite.emailInvite": "Convite por email",
    "invite.viewTesterMembers": "Ver membros de teste",
    "invite.thisWorkspace": "esta workspace",
    "invite.sourceWorkspace": "Workspace de origem",
    "invite.currentWorkspace": "Workspace atual",
    "invite.internalMembers": "Membros internos",
    "invite.pendingInvites": "Convites pendentes",
    "invite.emailSetupReady": "Configuração de email de convite pronta",
    "invite.emailSetupAttention": "A configuração de email precisa de atenção",
    "invite.emailConfigured": "APP_URL, RESEND_API_KEY e EMAIL_FROM estão configurados com um remetente que não é de desenvolvimento.",
    "invite.emailBlocked": "Os convites ficam bloqueados até que a entrega pelo Resend esteja configurada e aceita.",
    "invite.missing": "Faltando: {keys}.",
    "invite.setVerifiedSender": "Defina EMAIL_FROM com um remetente verificado no Resend.",
    "invite.lastTest": "Último teste {time}: {message}",
    "invite.testing": "Testando...",
    "invite.sendTest": "Enviar teste",
    "invite.titleDefault": "Convidar para equipe",
    "invite.descriptionDefault": "Enviaremos um link de convite por email para cada endereço.",
    "invite.submitDefault": "Enviar convites",
    "invite.successDefault": "Convidado",
    "invite.emailLabel": "Emails (separados por vírgula ou nova linha)",
    "invite.addAtLeastOne": "Adicione pelo menos um email",
    "invite.couldNotSend": "Não foi possível enviar os convites",
    "invite.deliveryNotConfirmed": "A entrega do email de convite não foi confirmada",
    "invite.teammate": "membro",
    "invite.teammates": "membros",
    "invite.mode": "Modo do convite",
    "invite.ownWorkspace": "Própria workspace",
    "invite.workspaceAccess": "Esta workspace",
    "invite.workspaceModeHint": "Eles entram nesta workspace e aparecem como membros da equipe depois do aceite.",
    "invite.personalModeHint": "Eles recebem a própria workspace do UP Flow e não veem esta workspace.",
    "invite.role": "Função",
    "invite.appUrlMissing": "Defina APP_URL como a URL pública canônica do app e reinicie o app.",
    "invite.emailNotConfigured": "Defina RESEND_API_KEY e EMAIL_FROM com um remetente verificado no Resend, depois reinicie o app.",
    "invite.emailSendFailed": "Verifique o painel do Resend, a chave de API, a verificação do remetente, as restrições de destinatário e a mensagem do provedor.",
    "invite.checkSetup": "Verifique a configuração de email de convite e tente novamente.",
    "invite.notFound": "Convite não encontrado",
    "invite.loadFailed": "Falha ao carregar convite",
    "invite.acceptFailed": "Não foi possível aceitar o convite",
    "invite.signInFailed": "Não foi possível entrar com essa senha.",
    "invite.signInAcceptFailed": "Login feito, mas não foi possível aceitar o convite.",
    "invite.accountExists": "Já existe uma conta para este email. Entre para aceitar.",
    "invite.createAccountFailed": "Não foi possível criar a conta",
    "invite.createAccount": "Criar conta",
    "invite.pageTitle": "Você foi convidado",
    "invite.loading": "Carregando convite...",
    "invite.testerBadge": "Workspace de teste",
    "invite.workspaceAccessBadge": "Acesso a workspace",
    "invite.invitedBy": "{name} convidou você para usar",
    "invite.someone": "Alguém",
    "invite.productName": "Up Flow",
    "invite.inviteFor": "Convite para",
    "invite.testerExplanation": "Este convite abre uma workspace isolada de teste do UP Flow com projetos, clientes, reuniões, docs e tarefas de exemplo. Ele não concede acesso a workspaces reais de clientes.",
    "invite.workspaceAccessExplanation": "Este convite adiciona você a {workspace}. Depois de aceitar, você aparecerá como membro da equipe e poderá trabalhar com projetos, tarefas, eventos de calendário e clientes reais da workspace.",
    "invite.personalWorkspaceExplanation": "Este convite cria sua própria workspace do UP Flow para você usar a plataforma sem receber acesso a {workspace}.",
    "invite.email": "Email",
    "invite.fullName": "Nome completo",
    "invite.fullNamePlaceholder": "Seu nome completo",
    "invite.cellphone": "Celular",
    "invite.password": "Senha",
    "invite.passwordPlaceholder": "Mínimo de 8 caracteres",
    "invite.enterPassword": "Digite sua senha",
    "invite.creating": "Criando...",
    "invite.createAndOpen": "Criar conta e abrir workspace",
    "invite.signingIn": "Entrando...",
    "invite.signIn": "Entrar",
    "invite.signInAndOpen": "Entrar e abrir workspace",
    "invite.alreadySignedIn": "Já estou logado",
    "invite.fullLoginPrompt": "Precisa da página completa de login?",
    "invite.openSignIn": "Abrir login",
    "error.pageTitle": "Esta página não carregou",
    "error.pageBody": "O app não conseguiu terminar de carregar esta tela. Tente novamente primeiro. Se continuar acontecendo, volte para o dashboard e verifique o Admin Health para problemas de banco, Supabase ou configuração de email.",
    "error.reference": "Referência",
    "error.retryPage": "Tentar novamente",
    "error.openDashboard": "Abrir dashboard",
    "error.notFoundTitle": "Página não encontrada",
    "error.notFoundBody": "A página que você procurou não existe ou foi movida.",
    "error.backDashboard": "Voltar ao dashboard",
  },
};

const LanguageContext = React.createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => null,
  toggleLanguage: () => null,
  t: (key) => key,
});

function normalizeLanguage(value: string | null): Language | null {
  if (value === "en" || value === "pt-BR") return value;
  return null;
}

function interpolate(value: string, vars?: TranslationVars) {
  if (!vars) return value;
  return value.replace(/\{(\w+)\}/g, (_, key: string) =>
    Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : `{${key}}`,
  );
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = React.useState<Language>("en");

  React.useEffect(() => {
    try {
      const stored = normalizeLanguage(localStorage.getItem(STORAGE_KEY));
      if (stored) setLanguageState(stored);
    } catch {
      // localStorage can be unavailable in privacy modes; English stays as default.
    }
  }, []);

  const setLanguage = React.useCallback((next: Language) => {
    setLanguageState(next);
    try {
      localStorage.setItem(STORAGE_KEY, next);
    } catch {
      // Non-persistent language selection is still usable for the current session.
    }
  }, []);

  React.useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dataset.language = language;
  }, [language]);

  const value = React.useMemo<LanguageContextType>(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage(language === "en" ? "pt-BR" : "en"),
      t: (key, vars) => {
        const localized = translations[language][key] ?? translations.en[key] ?? key;
        return interpolate(localized, vars);
      },
    }),
    [language, setLanguage],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return React.useContext(LanguageContext);
}
